.PHONY: build up down status logs shell test

build:
	docker compose build

up:
	./scripts/linux-gui up

down:
	./scripts/linux-gui down

status:
	./scripts/linux-gui status

logs:
	./scripts/linux-gui logs

shell:
	./scripts/linux-gui shell

test:
	./tests/smoke.sh
